sudo: required

services:
  - docker

language: node_js
node_js:
  - "5"

script:
  - cd client && npm run build
after_success:
  - docker build --tag="szazo/fctime:dev" --file=docker/dev/web/Dockerfile ./client
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push szazo/fctime:dev
